header: Layanan
calendly:
  15min: https://calendly.com/nutriolab-id/15min-free-introductory-consultation
  50min: https://calendly.com/nutriolab-id/60min-general-consultation
packages:
  - name:
    options:
      - title:
        name: Panggilan Pendahuluan Gratis
        description: 
          normal: Gratis! Beri tahu kami masalah Anda dan kami siap membantu Anda! Daftar sekarang untuk mendapatkan panggilan gratis!
        services:
          - ++ Konsultasi (15 min)
        price:
          text: Daftar sekarang!
        calendly_type: 15min
      - title:
        name: Konsultasi Umum
        description: 
          normal: Konsultasi hingga 50 menit terkait permasalahan teknis yang lebih spesifik dengan spesialis kami. Anda akan mendapatkan ringkasan dari pertemuan konsultasi.
        services:
          - ++ Konsultasi (50 min)
        price:
          text:
          cardinal: kontak kami
        calendly_type: 50min
  - name: Layanan Teknis
    options:
      - title: T01
        name:  Label dan Klaim Gizi
        description: 
          bold: Sekarang Anda bisa memberikan label gizi pada produk Anda! Tunjukkan betapa bergizinya produk Anda!
          normal: Label, klaim, dan rekomendasi nilai gizi.
        price:
          text: 'Hubungi kami untuk harga'
        email: true
      - title: T02
        name: Profil Produk
        description: 
          bold: Pahami produk Anda seperti memahami pacar Anda!
          normal: Profil risiko, penilaian kualitas & keamanan pangan, evaluasi sensori, studi umur simpan, pemilihan kemasan.
        price:
          text: 'Hubungi kami untuk harga'
        email: true
      - title: T03
        name: Roadmap Optimasi Proses
        description: 
          bold: Hemat waktu dan uang Anda dengan mengoptimalkan desain proses Anda!
          normal: Proses standar, parameter & spesifikasi proses, rancangan HACCP
        price:
          text: 'Hubungi kami untuk harga'
        email: true
      - title: T04
        name: Roadmap Peningkatan Skala Produksi
        description: 
          bold: Bisnis Anda berkembang pesat? Saatnya untuk meningkatkannya! Sekarang Anda dapat mengubah garasi Anda menjadi industri pangan kecil!
          normal: Manajemen produksi, standar proses, parameter & spesifikasi proses, rencana HACCP
        price:
          text: 'Hubungi kami untuk harga'
        email: true
  - name: Layanan perencanaan sertifikasi dan regulasi
    options:
      - title: R01
        name: Roadmap Sertifikasi Halal
        description: 
          bold: Lebih percaya diri terhadap produk Anda dengan mematuhi standar!
          normal: Perencanaan dan persyaratan sertifikasi halal.
        price:
          text: 'Hubungi kami untuk harga'
        email: true
      - title: R02
        name: Sertifikasi Regulasi Lainnya
        description: 
          bold: Kami sedang mengerjakannya, kami akan menginformasikan Anda segera.
          normal: Jangan ragu untuk menghubungi kami jika Anda tertarik.
        price:
          text: 'segera hadir'
        email: true
postPackages:
  title: Pertanyaan lainnya
  message: Permasalahan Anda tidak tertera pada informasi di atas? Beri tahu kami melalui panggilan pendahuluan gratis atau pertanyaan umum.
cta:
  name: konsultasikan dengan kami
  link: /kontak
---
