header: Services
calendly:
  15min: https://calendly.com/nutriolab-id/15min-free-introductory-consultation
  50min: https://calendly.com/nutriolab-id/60min-general-consultation
packages:
  - name:
    options:
      - title:
        name: Free Introductory Call
        description: 
          normal: It’s FREE! Tell us your problem and we are ready to help you! Sign up now to get your free call!
        services:
          - ++ Consultation (15 min)
        price:
          text: 'Sign Up Now!'
        calendly_type: 15min
      - title:
        name: General Consultancy
        description: 
          normal: Consult up to 50 mins for more specific technical issues with our tailored specialist. You will get a summary of the consultancy meeting.
        services:
          - ++ Consultation (50 min)
          - ++ Report Delivery
        price:
          Text: contact us
        calendly_type: 50min
  - name: Technical Services
    options:
      - title: T01
        name: Nutrition Labelling & Claim
        description: 
          bold: Now you can put the nutrition label on your product! Showcase how nutritious your product is! 
          normal: Nutrition facts label, claim suggestions
        price:
          text: 'contact us for pricing'
        email: true
      - title: T02
        name: Product Profiling
        description: 
          bold: Understand your product like understanding your girlfriend! 
          normal: Risk profile, quality & safety assessment, sensory evaluation, shelf-life study, packaging selection
        price:
          text: 'contact us for pricing'
        email: true
      - title: T03
        name: Process Optimization Roadmap
        description: 
          bold: Save up your time and money by optimizing your process design! 
          normal: Standardized process, process parameter & specification, HACCP plan
        price:
          text: 'contact us for pricing'
        email: true
      - title: T04
        name: Production Scale-up Roadmap
        description: 
          bold: Your business is growing quickly? Time to scale it up! Now you can turn your garage into a small food factory!
          normal: production management, standardized process, process parameter & specification, HACCP Plan 
        price:
          text: 'contact us for pricing'
        email: true
  - name: Certification Planning & Regulatory Services
    options:
      - title: R01
        name: Halal Certification Roadmap
        description: 
          bold: Be more confident in your product by complying to the standard!
          normal: Halal certification requirements and planning 
        price:
          text: 'contact us for pricing'
        email: true
      - title: R02
        name: Other Regulatory Certification
        description: 
          bold: We’re working on it, we’ll bring it to you as soon as possible.
          normal: Feel free to contact us if you’re interested
        price:
          text: 'coming soon'
        email: true
postPackages:
  title: Other inquiries
  message: Don’t see you issues up there? Let us know through complementary introductory call or general inquires.
cta:
  name: consult with us
  link: /contact
---
